### ISSUE TITLE
the data in table does't match the column.

### ISSUE THREAD

**Issue by AisTop** [shunfei/indexr#13]
Hi flowbehappy. my problem is here 
![image](https://cloud.githubusercontent.com/assets/13936168/21917251/86beffcc-d981-11e6-9737-b649e83244a5.png)
in the top two rows , is the wrong value in the  table schema  column .    
**describer:**     the  json  data   key is  60 .  and the table schema column is 63.  the json data key order is not match the table  schema .
in the botton one rows  is the right value in the  table schema column.
**describer**    the json data  key    is 63   which match the table schema . and order is match both.

could i add you QQ or email .  i's  makes me convenient to contact you .
my  qq is  2545392961    email is   hejianjunhtc@163.com 
glad to hear you  news

**Comment by flowbehappy** [comment]
ok
