### ISSUE TITLE
hi,I compiled indexr-0.2.1-bugfix2 encountered an error!

### ISSUE THREAD

**Issue by ikexu** [shunfei/indexr#16]
I compiled indexr-0.2.1-bugfix2 encountered an error：
Failed to execute goal on project indexr-query-opt: Could not resolve dependencies for project io.indexr:indexr-query-opt:jar:0.2.1: The following artifacts could not be resolved: io.indexr:indexr-common:jar:0.2.1, com.google.guava:guava:jar:16.0.1, org.apache.hadoop:hadoop-client:jar:2.6.0-cdh5.7.1: Could not find artifact io.indexr:indexr-common:jar:0.2.1 in central (https://repo.maven.apache.org/maven2)
I only modified hadoop.version for 2.6.0-cdh5.7.1,but i compiled  release-0.2.0 successed.
Hope to get help, thanks!

**Comment by flowbehappy** [comment]
@meitianxiaoxu 

It looks like indexr-common module has failed to compile. You can compile it separately, check if there are any errors.
```
mvn clean install -DskipTests=true -pl indexr-common
```

**Comment by ikexu** [comment]
@flowbehappy 
Rigth,indexr-common module has failed to compile,The reason is that I specified hadoop.version is 2.6.0-cdh5.7.1, i should added  the cloudera maven repository in pom.xml。Not only that, I also need to add the main directory pom.xml in the local library , because the compiler indexr-query-opt need this pom。
