### ISSUE TITLE
Using jdk1.7 compiler indexr will have unpredictable problems?

### ISSUE THREAD

**Issue by ikexu** [shunfei/indexr#17]
I started using jdk1.8 compiler, but the production environment is jdk1.7, now must be used jdk1.7 to compile, I would like to know there will be unpredictable problems?

**Comment by ikexu** [comment]
Because I found that [Compilation Compilation ](https://github.com/shunfei/indexr/wiki/Compilation) 
specified JDK 1.8+

I saw the source code found a lot of jdk1.8 syntax, it can not compiled with jdk1.7...

**Comment by flowbehappy** [comment]
@meitianxiaoxu 
Highly suggest upgrade to 1.8. We have done it a year ago and nothing bad happen, with performance improved and nice GC latency.
