### ISSUE TITLE
Maven compile problem

### ISSUE THREAD

**Issue by listenLearning** [shunfei/indexr#19]
Try to compile indexR today, there has been a can not find this BhcompressLibrary package error, how can this solution

**Comment by flowbehappy** [comment]
@listenLearning 

Please follow the instructions here to compile IndexR:
https://github.com/shunfei/indexr/wiki/Compilation#build-indexr

BhcompressLibrary.java is generated by `script/setup_indexr-segment.sh` script.

**Comment by listenLearning** [comment]
I follow the compilation method on github to compile, in the drill here encountered some problems, I can not use github checkout out indexr-0.4.2-drill-1.10.0, there is a problem: Not a git repository (or any of The parent directories: .git
