### ISSUE TITLE
Can't parallelize fragment: Every mandatory node has exhausted the maximum width per node limit.

### ISSUE THREAD

**Issue by yourfrienddhruv** [shunfei/indexr#22]
Evaluating Indexr on existing HDP2.5 , Drill 1.9.0 cluster 
Based on https://github.com/shunfei/indexr/wiki/Deployment instructions created following table

`{
  "schema": {
    "columns": [
      {
        "name": "host_id",
        "dataType": "int"
      },
      {
        "name": "host_name",
        "dataType": "string"
      },
      {
        "name": "cpu_count",
        "dataType": "int"
      }
    ]
  },
  "location": "/indexr/segment/hosts",
  "mode": "vlt",
  "agg": {
    "grouping": true,
    "dims": [
      "host_id",
      "host_name"
    ],
    "metrics": [
      {
        "name": "cpu_count",
        "agg": "min"
      }
    ]
  },
  "realtime": {
    "save.period.minutes": 20,
    "upload.period.minutes": 60,
    "max.row.memory": 500000,
    "max.row.realtime": 10000000,
    "fetcher": {
      "type": "kafka-0.8",
      "topic": "pg_imp1",
      "number.empty.as.zero": false,
      "properties": {
        "zookeeper.connect": "drsahmd2.is.com:2181,drsahmd3.is.com:2181,drsahmd4.is.com:2181",
        "zookeeper.connection.timeout.ms": "15000",
        "zookeeper.session.timeout.ms": "40000",
        "zookeeper.sync.time.ms": "5000",
        "fetch.message.max.bytes": "1048586",
        "auto.offset.reset": "largest",
        "auto.commit.enable": "true",
        "auto.commit.interval.ms": "5000",
        "group.id": "c2"
      }
    }
  }
}
`
All OK, no errors in log, for deployments or enabling realtime stuff too.
But QUERIES fails with following error. Same error with or without realtime enabled.
Our use case is we dynamically create tables and let query return empty results IF there are NO DATA yet.

`select * from indexr.hosts limit 10` 

SHOULD return NO RESULTS
but instead FAILS

`2017-09-13 18:40:56,232 [2646d19f-bd5d-5eb5-ee18-90b2022076e2:foreman] ERROR o.a.d.e.p.f.HardAffinityFragmentParallelizer - Can't parallelize fragment: Every mandatory node has exhausted the maximum width per node limit.
Endpoint pool: {address: "drsahmd3.is.com"
user_port: 31010
control_port: 31011
data_port: 31012
=EndpointAffinity [endpoint=address: "drsahmd3.is.com" user_port: 31010 control_port: 31011 data_port: 31012, affinity=0.0, mandatory=true, maxWidth=2147483647]}
Assignment so far: {address: "drsahmd3.is.com"
user_port: 31010
control_port: 31011
data_port: 31012
=1}
Width: 2
2017-09-13 18:40:56,300 [2646d19f-bd5d-5eb5-ee18-90b2022076e2:foreman] ERROR o.a.drill.exec.work.foreman.Foreman - SYSTEM ERROR: PhysicalOperatorSetupException: Can not parallelize fragment.
`

We have 3 DN, 3replicatoin , 3 Colocated Drillbits

> 
>  bin/tools.sh -cmd listrs -t hosts
> rt/rtsg.201709131831.94ecc793-b374-4294-bfe5-64183d62fdb2.seg:
> ----------
> host: drsahmd3.is.com
> rowCount: 0
> version: 8
> mode: vlt
> 
> bin/tools.sh -cmd lisths -t hosts
> bin/tools.sh -cmd rttnode -t hosts
> hosts:
>  -----------
> drsahmd3.is.com
> 
>  bin/tools.sh -cmd listnode
> drsahmd3.is.com
> drsahmd4.is.com
> drsahmd5.is.com
> 

Issue: Is this expected behaviour for EMPTY tables?

P.S.: Thank you guys for open sourcing such an amazing work ( We kind of know the hard work goes behind this, as we also built and evolved a system with same objective from past few years)

**Comment by flowbehappy** [comment]
@yourfrienddhruv 
Hi, it is a bug of indexr drill plugin. It should be fixed by commit https://github.com/shunfei/drill/commit/dcf9f030c6c3504cf58b6dc637b5c14234f7b293 , right now you can fetch it to your branch indexr-0.6.0-drill-1.9.0 and see if it help.

This commit will be added into official branch after 0.6.1 is release.

**Comment by yourfrienddhruv** [comment]
Thanks for the prompt response! We would try out that commit, and post an update.

**Comment by yourfrienddhruv** [comment]
Hi @flowbehappy , can you guys help us a bit to get our build through?

We tried to build https://github.com/shunfei/drill/tree/indexr-0.6.0-drill-1.9.0/contrib/storage-indexr Which will give me FIXED version of indexr plugin jar

Which actually required us to build https://github.com/shunfei/indexr/ locally ( guess jars are not published on maven-central?), which in turns fail with below error.

`
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.382 s
[INFO] Finished at: 2017-09-15T16:43:09+05:30
[INFO] Final Memory: 33M/427M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project indexr-segment: Compilation failure: Compilation failure: 
[ERROR] /home/dhruv.gohil/github/indexr/indexr-segment/src/main/java/io/indexr/compress/bh/BHCompressor.java:[46,37] package BhcompressLibrary does not exist
`

We are not able to find source codes / make / build for this binary. 
A) Can you point us to build instructions for this library?  (FYI : We are building on ubuntu/REHL machines)
B) Can you point us to right way to build this if above stated is not in correct order?
C) We are OK to move to latest version of DRILL if things are more simpler to build/patch/contribute back.

**Comment by yourfrienddhruv** [comment]
Sorry for that silly question but we found out https://github.com/shunfei/indexr-compress-lib :-)
And found out all scripts , and triggered build using : 
https://github.com/shunfei/indexr/blob/master/script/release_artifact.sh

C) But I guess we still are missing a way to add that native lib to MavenBuildPath ? 
D) are below steps correct?

```
m1:~/github/indexr-compress-lib$ ./compile.sh 
 Generated /home/m1/github/indexr-compress-lib/lib/libbhcompress.so
 m1:~/github/indexr-compress-lib$ sudo ln -s  /home/m1/github/indexr-compress-lib/lib/libbhcompress.so /usr/local/lib/

```

**Comment by flowbehappy** [comment]
Hi, the `libbhcompress.so` is only used in `basic` mode. And by default we use `vlt` mode. 
You can simply deploy it to target machines by putting it under `/usr/local/lib/`.

**Comment by yourfrienddhruv** [comment]
Hi @flowbehappy , Got it about basic vs VLT mode dependency on libbhcompress.so at runtime.
But right now we are trying to apply your suggested patch to build indexr plugin for drill.

So, we are trying to build https://github.com/shunfei/drill/tree/indexr-0.6.0-drill-1.9.0/contrib/storage-indexr 

And for that we are tying to build https://github.com/shunfei/indexr/ locally ( guess jars are not published on maven-central?), which in turn is failing with below error. 
we already have /usr/local/lib//libbhcompress.so on build machine.

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project indexr-segment: Compilation failure: Compilation failure: [ERROR] /home/dhruv.gohil/github/indexr/indexr-segment/src/main/java/io/indexr/compress/bh/BHCompressor.java:[46,37] package BhcompressLibrary does not exist`

**Comment by flowbehappy** [comment]
You can follow the instruction here https://github.com/shunfei/indexr/wiki/Compilation to compile your new deployment package. `BhcompressLibrary` is a generated java class by `script/setup_all.sh` script.

**Comment by yourfrienddhruv** [comment]
Thanks @flowbehappy for being patient with us, the commit worked perfectly!
Never ever was so happy to see "No result found." ;-)
