### ISSUE TITLE
unable to create storage plugin

### ISSUE THREAD

**Issue by thbeh** [shunfei/indexr#25]
Hi, i am tseting indexR in MapR v6.0 and I have managed to get hive to work in your example but could not get to create drill stroage plugin in the web console.I tried the following

{
  "type": "indexr",
  "enabled": true
}

but web console kept complaining error (unable to create/update storage). Did I missed any part?

**Comment by flowbehappy** [comment]
Hi, please check drillbit.log for errors. 
Mostly because of jars not correctly deployed.
