### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mseaspring** [shunfei/indexr#26]
我想请教下编译这源码的顺序，发现编译有不少错误，比如indexr-query-opt工程的AstListener.java代码
提升：
import io.indexr.query.parsers.RQLBaseListener;
import io.indexr.query.parsers.RQLParser; 
两个库不存在。
请教有没有具体的编译源码手册。

**Comment by flowbehappy** [comment]
You should first run the setup scripts. Those files are generated.
