### ISSUE TITLE
drill新建storage失败

### ISSUE THREAD

**Issue by ZBHdd** [shunfei/indexr#33]
![image](https://user-images.githubusercontent.com/30063654/55952192-95814f80-5c8b-11e9-8a3a-344b4208868e.png)
drill新建indexR storage失败
Please retry: Error while creating/ updating storage : org.apache.drill.exec.store.AbstractStoragePlugin: method <init>()V not found

**Comment by lbovery** [comment]
哥们，这个问题你怎么解决的

**Comment by ZBHdd** [comment]
好像是 版本有问题

**Comment by lbovery** [comment]
> 好像是 版本有问题
drill的版本？

**Comment by ZBHdd** [comment]
> > 好像是 版本有问题
> > drill的版本？

嗯，之前是最高支持 drill 1.13，不知道更新没，你可以去群里问问

**Comment by lbovery** [comment]
关键是官网已经把drill1.15前的包下架了

**Comment by lbovery** [comment]
我去github上找源码编译吧

**Comment by ZBHdd** [comment]
> 我去github上找源码编译吧

官网好像有个 历史仓库，那里有

**Comment by ZBHdd** [comment]
> > 我去github上找源码编译吧
> 
> 官网好像有个 历史仓库，那里有

http://archive.apache.org/dist/drill/
