### ISSUE TITLE
我是否可以用impala来查询

### ISSUE THREAD

**Issue by ighack** [shunfei/indexr#35]
impala可以查hive
而hive可以查indexR
那我是否可以用impala->hive->indexR
这样查询
还有用户手册是不是可以提供中文版的啊

**Comment by flowbehappy** [comment]
impala 是 c++ 系的，它应该是支持了 hive 的格式，所以可以读取 hive 数据。但是 impala 目前没有支持 indexr 格式。所以是不可以的。
