### ISSUE TITLE
/usr/local/drill 目录下并没有bin/drill-conf文件啊

### ISSUE THREAD

**Issue by ghost** [shunfei/indexr#5]
如图：
![image](https://cloud.githubusercontent.com/assets/7246660/21742711/9a790f6e-d52e-11e6-9739-60a1fccd72ad.png)

![image](https://cloud.githubusercontent.com/assets/7246660/21742707/8552c53a-d52e-11e6-8898-4c6e6c8f12f5.png)

/usr/local/drill 是从indexr-<version>/indexr-drill/* 目录下拷过来的

**Comment by flowbehappy** [comment]
@vbvbipny 

You need to install Apache Drill first, before deploying IndexR Drill plugin.
https://github.com/shunfei/indexr/wiki/Deployment#system-requirements
