### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class io.indexr.compress.bh.BhcompressLibrary

### ISSUE THREAD

**Issue by AisTop** [shunfei/indexr#7]
Hi   I meet e error .  could not initialize class BhcompressLibrary.  
but i don‘t find the class in the class path  io.indexr.compress.bh 。
and my ide also has a error which is could not resove the class   BhcompressLibrary.

![image](https://cloud.githubusercontent.com/assets/13936168/21794974/e93e6556-d739-11e6-81f9-421613723081.png)
![image](https://cloud.githubusercontent.com/assets/13936168/21795001/1be602f2-d73a-11e6-9c51-3473f82c9788.png)

my error  message is：
[IndexR-RT-Handle-0] ERROR io.indexr.segment.rt.RTSGroup - Save in memory rows to disk failed. [table: kafka_test, rtsg: rt/rtsg.201701091144.fe1da5a7-3a36-4b6a-a844-1586103ecacb.seg, segment: rts.201701091145.90316abe-1e6c-40b0-9333-197efcdf440b.seg]
java.lang.NoClassDefFoundError: Could not initialize class io.indexr.compress.bh.BhcompressLibrary
	at io.indexr.compress.bh.BHCompressor.compressInt(BHCompressor.java:68) ~[indexr-segment-0.1.0.jar:na]
	at io.indexr.segment.pack.NumOp.compress(NumOp.java:68) ~[indexr-segment-0.1.0.jar:na]

**Comment by flowbehappy** [comment]
@AisTop 

This class is generated by `jnaerator` from `javaCompress.h`.
You should run the setup scripts before exploring the code. i.e.

```
sh script/setup_lib.sh
sh script/setup_indexr-segment.sh
sh script/setup_indexr-query.sh
```

**Comment by AisTop** [comment]
think you very much! it solve my problem.
