### ISSUE TITLE
i could not  consume data in my own table， how should id do .

### ISSUE THREAD

**Issue by AisTop** [shunfei/indexr#8]
i found some msg  is here ===
11:26:31.575 [RT-Ingest-auth_data] INFO  io.indexr.segment.rt.RealtimeSegment - Table [auth_data]: consume msgs [6], fail msgs [5], ignore rows [1], produce rows [0], ingest rows [0], final rows [0], took time [1905.71s], consume memory [0K], total rt memoryusage [0M], avaliable memory [50822M], segment: [rts.201701111054.af068ccd-79f4-427c-b24b-e4047db6b6f5.seg]
11:26:31.575 [RT-Ingest-auth_data] INFO  io.indexr.segment.rt.RealtimeTable - Finish ingest segment. [ingested: 0, got: 0 (NaN%)]. [table: auth_data, rtsg: rt/rtsg.201701111047.26de00b2-dc8c-4c47-846f-283595f69f78.seg, segment: rts.201701111054.af068ccd-79f4-427c-b24b-e4047db6b6f5.seg]
what i could do, to find the reason fail msgs[5].
fail msgs [5], ignore rows [1], produce rows [0] 

in the  table  schma  ,i turn off the grouping . and remove the dims and metrics.

think you very much

**Comment by AisTop** [comment]
does it has any limits in the table column numbers, my table column number is 63.  
or  it's matter with the order . the column order and the data column order.

**Comment by flowbehappy** [comment]
@AisTop 

IndexR limits column count to 65536, so 63 is fine. And the order does not matter, because the event is just a k-v map.

Current realtime ingestion by `kafka-0.8` fail only  because of  malformed json events. You should check your messages carefully.  You can post  your table schema and messages here.

**Comment by flowbehappy** [comment]
And, if you want to find the detail parsing errors, you can set the log level of `io.indexr.util.UTF8JsonDeserializer` to `trace` .
